/**
 * Anime API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiMoviesGet200ResponseInner { 
    _id?: string;
    genres?: Array<string>;
    title?: string;
    num_mflix_comments?: number;
    poster?: string;
    fullplot?: string;
    cast?: Array<string>;
    year?: number;
    type?: string;
}

